name: Check Test Coverage
on:
  pull_request:
#    branchs:
#      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run Coverage
        run: mvn clean test jacoco:report


      - name: Check Coverage
        run: |
          # Extrair cobertura total do arquivo de relatório do JaCoCo
          COVERAGE=$(grep -oP '(?<=<counter type="INSTRUCTION" missed=")[^"]+' target/site/jacoco/jacoco.xml)
          COVERED=$(grep -oP '(?<=<counter type="INSTRUCTION" covered=")[^"]+' target/site/jacoco/jacoco.xml)
          TOTAL=$((COVERED + COVERAGE))
          PERCENTAGE=$((100 * COVERED / TOTAL))
          
          echo "Cobertura: $PERCENTAGE%"
          
          if [ "$PERCENTAGE" -lt 80 ]; then
            echo "Cobertura abaixo de 80%! ($PERCENTAGE%)"
            exit 1
          else
            echo "Cobertura aceita: $PERCENTAGE%"
          ficore.setFailed('Overall coverage is less than 80%!')